version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Run shellcheck
          command: shellcheck ./shwain

  build:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Pull required bats submodules for testing
          command: |
            git submodule init
            git submodule update --remote

      - run: npm install bats --save-dev

      - run:
          name: Test CLI
          command: node_modules/bats/bin/bats test/shwain-cli.bats

      - run:
          name: Test API
          command: node_modules/bats/bin/bats test/shwain-api.bats

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

workflows:
  version: 2
  build-workflow:
    jobs:
      - shellcheck
      - build:
          requires:
            - shellcheck
          filters:
            tags:
              only: /.*/
